#!/bin/zsh

brewcaskinstall "Firefox"
dockutil --no-restart --add "/Applications/Firefox.app" --before "Safari"

brewcaskinstall "Google Chrome"
dockutil --no-restart --add "/Applications/Google Chrome.app" --after "Safari"

brewcaskinstall "Opera"

brewcaskinstall "Utilities/Adobe Flash Player Install Manager" "flash"
brewcaskinstall "/Library/Internet Plug-Ins/googletalkbrowserplugin.plugin" "google-hangouts"

killosxprefs
killosxdock
