#!/bin/zsh

# define zsh as default shell
chsh -s /bin/zsh $USER

# If we are under a Mac OS X platform   
if [[ "$(uname -s)" == "Darwin" ]]
then
  echo "Before running myself, please be sure you have 'git' command working".
  echo ""
  echo "In order to skip the following message:"
  echo "'Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.'"
  echo "You can run"
  echo "  sudo xcodebuild -license"
  echo "or just open Xcode and agree to the license."
  echo ""
  echo "You may need Xcode Command-Line Tools"
  echo "You can try the following if you are on a stable OS X version (with stable Xcode)"
  echo "  xcode-select --install"
  echo ""
  echo "Press return when 'git' command is available"
  read -k
fi

# If the dotfiles directory does not exist in $HOME
# git clone it! If it exist, pull and update it.
if [[ ! -d $HOME/dotfiles ]]
then
  git clone http://github.com/Macxim/dotfiles.git $HOME/dotfiles
  git submodule init
else
  cd $HOME/dotfiles
  git pull
fi
git submodule update

if [[ ! -d $HOME/dotfiles/.git ]]
then
  echo "dotfiles have not been downloaded correctly"
  echo ""
  echo "Aborting"

else
  echo "dotfiles have been downloaded"
  echo ""
  echo "Running installation"

  if [[ ! -d $HOME/Applications ]]
  then
    mkdir $HOME/Applications
  fi

  . $HOME/dotfiles/bin/hajime --full

  if ! type "say" > /dev/null
  then
    say "Setup is done \!"
  fi
fi
