#!/bin/zsh

# define zsh as default shell
chsh -s /bin/zsh $USER

read -q "xcode?Did you downloaded and installed Xcode from the App Store? (y/n) \n" 
if [[ "$xcode" =~ ^[Yy]$ ]]
then
  echo "Good! Now install Xcode CLI tools with `xcode-select --install`"
  echo "Next. Agree to Xcode License Agreements with `sudo xcodebuild -license`"
fi


# If the dotfiles directory does not exist in $HOME
# git clone it! If it exists, pull and update it.
if [[ ! -d $HOME/dotfiles ]]
then
  git clone http://github.com/Macxim/dotfiles.git $HOME/dotfiles
else
  cd $HOME/dotfiles
  git pull
fi


if [[ ! -d $HOME/dotfiles/.git ]]
then
  echo "Dotfiles have not been downloaded correctly. Aborting."
else
  echo "Dotfiles have been downloaded. Let's proceed."
  . $HOME/dotfiles/bin/zas --full
fi
