#!/bin/zsh

# define zsh as default shell
chsh -s /bin/zsh $USER

# If the dotfiles directory does not exist in $HOME
# git clone it! If it exists, pull and update it.
if [[ ! -d $HOME/dotfiles ]]
then
  git clone http://github.com/Macxim/dotfiles.git $HOME/dotfiles
  git submodule init
else
  cd $HOME/dotfiles
  git pull
fi
git submodule update

if [[ ! -d $HOME/dotfiles/.git ]]
then
  echo "Dotfiles have not been downloaded correctly. Aborting."
else
  echo "Dotfiles have been downloaded. Let's proceed."
  . $HOME/dotfiles/bin/zas --full
fi
