#!/bin/zsh

# Development
brewinstall wget
brewinstall mysql
brewinstall memcached
brewinstall postgres
brewinstall redis
brewinstall mongodb

# Browsers
brewcaskinstall google-chrome
brewcaskinstall firefox

# Editor
brewcaskinstall visual-studio-code

# Windows management
brewcaskinstall spectacle

# Music/Video Players
brewcaskinstall vlc
brewcaskinstall mplayerx
brewcaskinstall webtorrent
brewcaskinstall iina
brewcaskinstall spotify

# Gif maker
brewcaskinstall licecap

# Disk Usage Utility
brewcaskinstall grandperspective

# Status bar for syncthing
brewinstall syncthing
brew services start syncthing
brewcaskinstall syncthing-bar

# Adapt computer's display to the time of day
brewcaskinstall flux

# Image Optimization
brewcaskinstall imageoptim

# Screenshots sharing
brewcaskinstall cloudup

# Chat apps
brewcaskinstall franz

# Cleaning
brewcaskinstall appcleaner

# Notetaking
brewcaskinstall nvalt

brewcaskinstall dropbox