#!/bin/zsh

###
# Transmission.app
###
brewcaskinstall "Transmission"

defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Torrents"
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true
defaults write org.m0k.transmission WarningDuplicate -bool false
defaults write org.m0k.transmission WarningDonate -bool false
defaults write org.m0k.transmission WarningLegal -bool false

# Upload/Download preferences
defaults write org.m0k.transmission QueueDownloadNumber 2
defaults write org.m0k.transmission SpeedLimitUploadLimit 5
defaults write org.m0k.transmission UploadLimit 5