#!/bin/zsh

defaults write com.apple.dock tilesize -int 36

# No bouncing icons
defaults write com.apple.dock no-bouncing -bool true

# Dim hidden apps
defaults write com.apple.dock showhidden -bool true

# Faster animation when switching spaces
defaults write com.apple.dock expose-animation-duration -float 0.15

# Minimize windows into their application’s icon
defaults write com.apple.dock minimize-to-application -bool true

# Minimize effect
defaults write com.apple.dock mineffect -string scale

# Enable spring loading for all Dock items
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

# Show indicator lights for open applications in the Dock
defaults write com.apple.dock show-process-indicators -bool true

# Dashboard.app not as a space
defaults write com.apple.dock dashboard-in-overlay -bool true

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false
