#!/bin/zsh

# Only use UTF-8 in Terminal.app
defaults write com.apple.terminal StringEncodings -array 4

# New tabs open with Default Working Directory
defaults write com.apple.Terminal NewTabWorkingDirectoryBehavior -bool true
