#!/bin/zsh

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable local Time Machine backups
# Doesn't work anymore on Mojave.
# hash tmutil &> /dev/null && sudo tmutil disablelocal
