#!/bin/zsh

# from AppStore
# todo get this app not from appstore
# https://github.com/TermiT/Flycut/issues/56
openifnot "Flycut" "/Applications/Flycut.app"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set stickyBezel 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set displayNum 40"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set rememberNum 99"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set menuIcon 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set loadOnStartup 1"
plistbuddy "Application Support/Flycut/com.generalarcade.flycut" "Set removeDuplicates 1"


brewcaskinstall "Prefs Editor" "prefs-editor"

# enhance OS X with some small utilities
# http://www.freemacsoft.net/appcleaner/
brewcaskinstall "AppCleaner" "appcleaner"

# http://shauninman.com/archive/2011/10/20/day_o_mac_menu_bar_clock
brewcaskinstall "Day-O" "day-o"
openifnot "Day-O" "/Applications/Day-O.app"

# http://brettterpstra.com/projects/nvalt/
brewcaskinstall "nvalt"
openifnot "nvALT" "/Applications/nvalt.app"

# https://justgetflux.com
brewcaskinstall "Flux"
openifnot "Flux" "/Applications/Flux.app"

# required by I don't know why
brewcaskinstall "Utilities/XQuartz" "xquartz"

# Trim enable for non Apple SSD
# brewcaskinstall "Trim Enabler"

# QuickLook plugins from https://github.com/sindresorhus/quick-look-plugins
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlcolorcode" "qlcolorcode"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlstephen" "qlstephen"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlmarkdown" "qlmarkdown"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-json" "quicklook-json"
brewcaskinstall "/opt/homebrew-cask/Caskroom/qlprettypatch" "qlprettypatch"
brewcaskinstall "/opt/homebrew-cask/Caskroom/quicklook-csv" "quicklook-csv"
brewcaskinstall "/opt/homebrew-cask/Caskroom/betterzipql" "betterzipql"
brewcaskinstall "/opt/homebrew-cask/Caskroom/webp-quicklook" "webp-quicklook"
brewcaskinstall "/opt/homebrew-cask/Caskroom/suspicious-package" "suspicious-package"

# reset QuickLook plugins
qlmanage -r &> /dev/null
