#!/bin/zsh

brewcaskinstall "Prefs Editor"

# enhance OS X with some small utilities
# http://www.freemacsoft.net/appcleaner/
brewcaskinstall "AppCleaner"

# http://shauninman.com/archive/2011/10/20/day_o_mac_menu_bar_clock
brewcaskinstall "Day-O"
defaults write com.shauninman.Day-O autoLaunch 1
defaults write com.shauninman.Day-O showIcon 1
defaults write com.shauninman.Day-O firstRun 0
defaults write com.shauninman.Day-O format "E HH:mm"
openifnot "Day-O" "/Applications/Day-O.app"

# http://brettterpstra.com/projects/nvalt/
brewcaskinstall "nvALT"

# https://justgetflux.com
brewcaskinstall "Flux"
openifnot "Flux"

# required by I don't know why
brewcaskinstall "Utilities/XQuartz" "xquartz"

# Trim enable for non Apple SSD
# brewcaskinstall "Trim Enabler"
