#!/bin/zsh


# Image Optimization
brewcaskinstall "ImageOptim" $HOME/Applications
brewcaskinstall "ImageAlpha" $HOME/Applications

# More utilities
brewcaskinstall "Transmit" $HOME/Applications

brewcaskinstall "Mou" $HOME/Applications

brewcaskinstall "NameChanger" $HOME/Applications

brewcaskinstall "GrandPerspective" $HOME/Applications

#brewcaskinstall "VirtualBox" $HOME/Applications

killosxprefs
killosxdock
