#!/bin/zsh


# Image Optimization
brewcaskinstall "ImageOptim"
brewcaskinstall "ImageAlpha"

# More utilities
brewcaskinstall "Mou"

brewcaskinstall "The Unarchiver"
brewcaskinstall "Keka"

brewcaskinstall "NameChanger"

brewcaskinstall "GrandPerspective"

#brewcaskinstall "VirtualBox"

killosxprefs
killosxdock
