#!/bin/zsh

# The purpose of this component
# is to build the Dock, one app at a time.
# Dock preferences are located in components/osx/preferences/Dock

echo_title_update "Dock"

dockutil --no-restart --remove all

dockApps=(
  "/Applications/Mail.app"
  "/Applications/FirefoxDeveloperEdition.app"
  "/Applications/Firefox.app"
  "/Applications/Atom.app"
  "/Applications/Utilities/Terminal.app"
  "/Applications/SourceTree.app"
  "/Applications/Transmit.app"
  "/Applications/nvALT.app"
  "/Applications/LimeChat.app"
  "/Applications/AppCleaner.app"
  )

for i in "${dockApps[@]}"
do
  dockutil --no-restart --add $i
done

dockutil --add '' --type spacer --section apps --after Mail
dockutil --add '' --type spacer --section apps --after Firefox
dockutil --add '' --type spacer --section apps --after Transmit
dockutil --add '' --type spacer --section apps --after LimeChat


# This is outside of the loop because I couldn't find a way
# to make it execute the dockutil parameters
# Probably due to a quote issue
dockutil --no-restart --add "~/Downloads" --view list --display folder --sort dateadded

killall Dock
