#!/bin/zsh

# The purpose of this component
# is to build the Dock, one app at a time.
# Dock preferences are located in components/osx/preferences/Dock

echo_title_update "Dock"

dockutil --no-restart --remove all

dockApps=(
  "/Applications/Mail.app"
  "/Applications/Calendar.app"
  "/Applications/Spotify.app"
  "/Applications/Firefox.app"
  "/Applications/Google Chrome.app"
  "/Applications/Safari.app"
  "/Applications/Visual Studio Code.app"
  "/Applications/Utilities/Terminal.app"
  "/Applications/SourceTree.app"
  "/Applications/Franz.app"
  "/Applications/AppCleaner.app"
  )

for i in "${dockApps[@]}"
do
  dockutil --no-restart --add $i
done

dockutil --add '' --type spacer --section apps --after Spotify
dockutil --add '' --type spacer --section apps --after Safari
dockutil --add '' --type spacer --section apps --after Franz


# This is outside of the loop because I couldn't find a way
# to make it execute the dockutil parameters
# Probably due to a quote issue
dockutil --no-restart --add "~/Downloads" --view list --display folder --sort dateadded

killall Dock
