#!/bin/zsh

if ! type "brew" > /dev/null
then
  echo_title_install "Homebrew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew doctor
else
  echo_title_update "Homebrew"
  brewu
  brew cleanup
fi

brew tap homebrew/dupes
brew tap homebrew/versions

# cask
brew tap caskroom/cask
brew tap caskroom/versions
brewinstall "brew-cask"
