#!/bin/zsh

brewinstall zsh-completions

source $DOTFILES/components/_cli/preferences/Terminal

# better than man
npmig tldr

# safer than rm
npmig trash

# essential missing commands to OSX
brewinstall tree
brewinstall ssh-copy-id

# to create favicons
brewinstall icoutils
