#!/bin/zsh

brewcaskinstall "Sublime Text" sublime-text3
dockutil --add '/Applications/Sublime Text.app'

# Make sure we can start Sublime Text from the command line.
ln -sf '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' /usr/local/bin/subl

# If the Installed Packages directory does not exist
# Create it!
ST3_INSTALLED_PACKAGES="$HOME/Library/Application Support/Sublime Text 3/Installed Packages"
if [[ ! -d $ST3_INSTALLED_PACKAGES ]]
then
  mkdir -p $ST3_INSTALLED_PACKAGES
fi

# Install the Package Control package if not already done.
if [[ ! -f "$ST3_INSTALLED_PACKAGES/Package Control.sublime-package" ]]
  then
    curl -so "$ST3_INSTALLED_PACKAGES/Package Control.sublime-package" https://sublime.wbond.net/Package%20Control.sublime-package
fi

ST3_PACKAGES="$HOME/Library/Application Support/Sublime Text 3/Packages"
# If the User directory does not exist in ST3_PACKAGES
# git clone it! If it exists, pull and update it.
if [[ ! -d $ST3_PACKAGES/User ]]
then
  echo_title_install "Sublime Text 3 User Preferences"
  git clone https://github.com/Macxim/sublime-text-settings.git $ST3_PACKAGES/User
else
  echo_title_update "Sublime Text 3 User Preferences"
  cd $ST3_PACKAGES/User
  git pull
fi

# If the Predawn directory does not exist in ST_PACKAGES
# git clone it! If it exists, pull and update it.
if [[ ! -d $ST3_PACKAGES/Predawn ]]
then
  echo_title_install "Predawn Theme for Sublime Text 3"
  git clone https://github.com/jamiewilson/predawn $ST3_PACKAGES/Predawn
else
  echo_title_update "Predawn Theme for Sublime Text 3"
  cd $ST3_PACKAGES/Predawn
  git pull
fi