#!/bin/zsh

brewinstall zsh-completions

source $DOTFILES/components/shell/preferences/terminal

# better than man
npmig tldr

# safer than rm
npmig trash

brewinstall tree
brewinstall heroku-toolbelt
